"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Globe2, Layers, Sparkles, X } from "lucide-react";
import type {
  BrandVoice,
  Duration,
  OfferModel,
  TravelerType,
  TravelStyle,
} from "@/lib/types";
import { enumValues } from "@/lib/schemas";
import { Button } from "@/components/ui/Button";
import { Card, CardContent } from "@/components/ui/Card";
import { useToast } from "@/components/ui";
import {
  CheckboxChip,
  FormField,
  Input,
  Select,
  Textarea,
} from "@/components/ui/field";
import { useProjectsStore } from "@/lib/store/projects-store";
import { useAiSettingsStore } from "@/lib/store/ai-settings-store";
import { useAiConfig } from "@/components/ai/AiConfigProvider";
import { estimateSeriesCost } from "@/lib/series/estimate";
import { runSeriesGeneration } from "@/lib/series/engine";
import { formatCostEstimate } from "@/lib/ai/pricing";
import { defaultRoute } from "@/lib/editions";
import { cn } from "@/lib/utils";
import { SUGGESTED_COUNTRIES } from "./countries";

/**
 * Batch series creator: one product spec + N countries. The first country
 * becomes the series original and every country is generated by the same
 * transposition pipeline. Text only by default; API images are opt-in.
 */
export function SeriesBatchForm() {
  const router = useRouter();
  const { toast } = useToast();
  const create = useProjectsStore((s) => s.create);
  const update = useProjectsStore((s) => s.update);
  const { config } = useAiConfig();
  const text = useAiSettingsStore((s) => s.text);
  const image = useAiSettingsStore((s) => s.image);
  const getApiKey = useAiSettingsStore((s) => s.getApiKey);

  const [concept, setConcept] = React.useState("");
  const [audience, setAudience] = React.useState("");
  const [positioning, setPositioning] = React.useState("");
  const [styles, setStyles] = React.useState<TravelStyle[]>([]);
  const [travelerType, setTravelerType] = React.useState<TravelerType>("Couple");
  const [duration, setDuration] = React.useState<Duration>("7 days");
  const [voice, setVoice] = React.useState<BrandVoice>("editorial");
  const [offerModel, setOfferModel] = React.useState<OfferModel>("digital");
  const [countries, setCountries] = React.useState<string[]>([]);
  const [query, setQuery] = React.useState("");
  const [withImages, setWithImages] = React.useState(false);
  const [starting, setStarting] = React.useState(false);

  const personalKey = getApiKey(text.provider);
  const provider = personalKey ? text.provider : "openai";
  const model = personalKey
    ? text.model
    : (config?.serverTextModel ?? text.model);
  const canRun = Boolean(personalKey || config?.serverOpenAiAvailable);

  const suggestions = SUGGESTED_COUNTRIES.filter(
    (name) =>
      name.toLowerCase().includes(query.trim().toLowerCase()) &&
      !countries.includes(name),
  ).slice(0, 8);

  // The estimate uses a stand-in spec with one edition of the chosen length.
  const estimate = React.useMemo(() => {
    if (!countries.length) return null;
    const dayCount = Number.parseInt(duration, 10);
    return estimateSeriesCost({
      source: {
        productionPlan: {
          editions: [
            {
              id: "spec",
              duration,
              travelerType,
              cities: [],
              route: [],
              createdAt: new Date().toISOString(),
              customDays: Number.isInteger(dayCount) ? undefined : undefined,
            },
          ],
        },
      } as never,
      countries: countries.length,
      provider,
      model,
      withImages,
      imageProvider: image.provider,
      imageModel: image.model,
      imageSize: image.size,
      imageQuality: image.quality,
    });
  }, [countries.length, duration, travelerType, provider, model, withImages, image]);

  function addCountry(name: string) {
    const trimmed = name.trim();
    if (!trimmed || countries.includes(trimmed)) return;
    setCountries((current) => [...current, trimmed]);
    setQuery("");
  }

  function start() {
    if (countries.length < 2 || starting || !concept.trim()) return;
    setStarting(true);
    try {
      const firstCountry = countries[0];
      const seriesId = crypto.randomUUID();
      const seriesName = `${concept.trim()} series`;

      // The first country's product is the series original, created as a
      // normal spec product and generated in place.
      const source = create({
        name: `${firstCountry} ${concept.trim()}`,
        country: firstCountry,
        positioning: positioning.trim(),
        targetAudience: audience.trim(),
        travelStyles: styles,
        travelerTypes: [travelerType],
        brandStyle: { voice },
        offerModel,
        channels: offerModel === "service" ? ["fiverr"] : ["etsy"],
        outputs: ["marketplace-listing", "pdf", "portfolio-visuals"],
      });
      const edition = {
        id: crypto.randomUUID(),
        duration,
        travelerType,
        cities: [],
        route: defaultRoute([], [], Number.parseInt(duration, 10)),
        createdAt: new Date().toISOString(),
      };
      update(source.id, {
        productionPlan: {
          ...source.productionPlan,
          editions: [edition],
        },
      });
      const sourceProject = useProjectsStore.getState().getById(source.id);
      if (!sourceProject) throw new Error("Could not create the series spec.");

      const imageKey = getApiKey(image.provider);
      const controller = new AbortController();
      void runSeriesGeneration({
        source: sourceProject,
        seriesId,
        seriesName,
        countries,
        generateSource: true,
        config: {
          provider,
          model,
          apiKey: personalKey || undefined,
          withImages,
          image: withImages
            ? {
                provider: imageKey ? image.provider : "openai",
                model: imageKey
                  ? image.model
                  : (config?.serverImageModel ?? image.model),
                apiKey: imageKey || undefined,
                size: image.size,
                quality: image.quality,
              }
            : undefined,
        },
        signal: controller.signal,
      }).catch(() => {
        // Per-country failures are tracked on the board.
      });

      router.push(`/series/${seriesId}`);
    } catch (error) {
      setStarting(false);
      toast(
        error instanceof Error ? error.message : "Could not start the series.",
        "error",
      );
    }
  }

  return (
    <div className="space-y-8">
      <Card>
        <CardContent className="space-y-6 p-6 sm:p-8">
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <FormField
              label="Product concept"
              htmlFor="series-concept"
              required
              hint="Names every product: e.g. “Food & Culture Itinerary” becomes “Japan Food & Culture Itinerary”."
            >
              <Input
                id="series-concept"
                value={concept}
                onChange={(event) => setConcept(event.target.value)}
                placeholder="e.g. Food & Culture Itinerary Product"
              />
            </FormField>
            <FormField label="Target audience" htmlFor="series-audience">
              <Input
                id="series-audience"
                value={audience}
                onChange={(event) => setAudience(event.target.value)}
                placeholder="e.g. First-time couples"
              />
            </FormField>
          </div>
          <FormField
            label="Positioning"
            htmlFor="series-positioning"
            hint="The shared promise every country version keeps."
          >
            <Textarea
              id="series-positioning"
              value={positioning}
              onChange={(event) => setPositioning(event.target.value)}
              placeholder="e.g. Human-paced routes built around food, neighborhoods, and rail."
            />
          </FormField>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
            <FormField label="Edition" htmlFor="series-duration">
              <Select
                id="series-duration"
                value={duration}
                onChange={(event) => setDuration(event.target.value as Duration)}
              >
                {enumValues.duration.map((item) => (
                  <option key={item}>{item}</option>
                ))}
              </Select>
            </FormField>
            <FormField label="Traveler type" htmlFor="series-traveler">
              <Select
                id="series-traveler"
                value={travelerType}
                onChange={(event) =>
                  setTravelerType(event.target.value as TravelerType)
                }
              >
                {enumValues.travelerType.map((item) => (
                  <option key={item}>{item}</option>
                ))}
              </Select>
            </FormField>
            <FormField label="Brand voice" htmlFor="series-voice">
              <Select
                id="series-voice"
                value={voice}
                onChange={(event) => setVoice(event.target.value as BrandVoice)}
              >
                <option value="editorial">Editorial &amp; warm</option>
                <option value="premium">Premium &amp; understated</option>
                <option value="friendly">Friendly &amp; practical</option>
                <option value="adventurous">Adventurous &amp; energetic</option>
              </Select>
            </FormField>
          </div>
          <FormField label="Travel styles">
            <div className="flex flex-wrap gap-2">
              {enumValues.travelStyle.map((style) => (
                <CheckboxChip
                  key={style}
                  label={style}
                  selected={styles.includes(style)}
                  onToggle={() =>
                    setStyles((current) =>
                      current.includes(style)
                        ? current.filter((item) => item !== style)
                        : [...current, style],
                    )
                  }
                />
              ))}
            </div>
          </FormField>
          <FormField label="Offer model" htmlFor="series-offer">
            <Select
              id="series-offer"
              value={offerModel}
              onChange={(event) =>
                setOfferModel(event.target.value as OfferModel)
              }
            >
              <option value="digital">Digital download</option>
              <option value="service">Custom service</option>
              <option value="hybrid">Hybrid</option>
            </Select>
          </FormField>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="space-y-6 p-6 sm:p-8">
          <FormField
            label="Countries"
            required
            hint="At least two. The first becomes the series original."
          >
            <Input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  event.preventDefault();
                  addCountry(suggestions[0] ?? query);
                }
              }}
              placeholder="Type a country and press Enter"
            />
          </FormField>
          {query && suggestions.length ? (
            <div className="flex flex-wrap gap-1.5">
              {suggestions.map((name) => (
                <button
                  key={name}
                  type="button"
                  onClick={() => addCountry(name)}
                  className="rounded-full border border-border-strong px-3 py-1 text-caption font-medium text-ink-soft transition-colors hover:border-forest/40 hover:text-ink"
                >
                  {name}
                </button>
              ))}
            </div>
          ) : null}
          {countries.length ? (
            <div className="flex flex-wrap gap-1.5">
              {countries.map((name, index) => (
                <span
                  key={name}
                  className="inline-flex items-center gap-1.5 rounded-full bg-sage-soft px-3 py-1.5 text-caption font-semibold text-forest"
                >
                  <Globe2 className="size-3.5" aria-hidden />
                  {name}
                  {index === 0 ? (
                    <span className="rounded-full bg-paper/80 px-1.5 text-[10px] uppercase tracking-wide">
                      Original
                    </span>
                  ) : null}
                  <button
                    type="button"
                    aria-label={`Remove ${name}`}
                    onClick={() =>
                      setCountries((current) =>
                        current.filter((item) => item !== name),
                      )
                    }
                    className="rounded-full p-0.5 hover:bg-paper/70"
                  >
                    <X className="size-3" />
                  </button>
                </span>
              ))}
            </div>
          ) : null}

          <fieldset className="space-y-2">
            <legend className="rc-label">Images</legend>
            <label
              className={cn(
                "flex cursor-pointer items-start gap-3 rounded-[var(--radius-card)] border p-4 transition-colors",
                !withImages
                  ? "border-forest bg-sage-soft/50"
                  : "border-border-soft hover:border-forest/30",
              )}
            >
              <input
                type="radio"
                name="batch-images"
                checked={!withImages}
                onChange={() => setWithImages(false)}
                className="mt-1 accent-[var(--rc-forest)]"
              />
              <span>
                <span className="block text-sm font-semibold text-ink">
                  Prompts only — recommended
                </span>
                <span className="mt-0.5 block text-caption leading-5 text-ink-soft">
                  Country-adapted image prompts for every product, ready to
                  paste into any external image tool. Zero API image cost.
                </span>
              </span>
            </label>
            <label
              className={cn(
                "flex cursor-pointer items-start gap-3 rounded-[var(--radius-card)] border p-4 transition-colors",
                withImages
                  ? "border-gold bg-gold-soft/40"
                  : "border-border-soft hover:border-forest/30",
              )}
            >
              <input
                type="radio"
                name="batch-images"
                checked={withImages}
                onChange={() => setWithImages(true)}
                className="mt-1 accent-[var(--rc-gold)]"
              />
              <span>
                <span className="block text-sm font-semibold text-ink">
                  Generate via API
                </span>
                <span className="mt-0.5 block text-caption leading-5 text-ink-soft">
                  Adds 6 billable images per country. Included in the estimate
                  below.
                </span>
              </span>
            </label>
          </fieldset>

          <div className="rounded-[var(--radius-card)] border border-[var(--rc-ai-border)] bg-[var(--rc-ai-surface)] p-4">
            <div className="flex items-center gap-2 text-sm font-semibold text-[var(--rc-ai-brown)]">
              <Sparkles className="size-4" aria-hidden />
              Estimated cost
            </div>
            {countries.length ? (
              <p className="mt-2 text-caption text-[var(--rc-ai-brown)]">
                <strong>{formatCostEstimate(estimate?.total ?? null)}</strong>{" "}
                for {countries.length} countr
                {countries.length === 1 ? "y" : "ies"} on {model}
                {personalKey ? " · your key" : " · RouteCrafter server key"}
              </p>
            ) : (
              <p className="mt-2 text-caption text-[var(--rc-ai-brown)] opacity-80">
                Add countries to see the estimate.
              </p>
            )}
          </div>

          {!canRun ? (
            <p className="text-caption text-terracotta">
              No AI credential available. Add a provider key in Settings, or
              enable the server key.
            </p>
          ) : null}
        </CardContent>
      </Card>

      <div className="flex justify-end">
        <Button
          disabled={countries.length < 2 || !concept.trim() || !canRun || starting}
          onClick={start}
        >
          <Layers className="size-4" />
          {starting
            ? "Starting…"
            : `Generate ${countries.length || ""} country products`}
        </Button>
      </div>
    </div>
  );
}
